### ISSUE TITLE
Turning off the indication when charging is connected

### ISSUE THREAD

**Issue by hachikoharuno** [halfmexican/battery-usage-wattmeter-extension#12]
Hello, when the charger is connected to the laptop, the N/A indicator lights up on the panel. Could you add in the extension settings the ability to disable this indication, so that when running on battery power, watts are shown, but when running on mains power, nothing is displayed?

**Comment by halfmexican** [comment]
This is doable.

**Comment by hachikoharuno** [comment]
This is very cool.  Thanks for your work!  I really like your extension.
