### ISSUE TITLE
[Suggestion] Remove unnecessary "-" and "0"

### ISSUE THREAD

**Issue by thafluu** [halfmexican/battery-usage-wattmeter-extension#15]
First I want to say thank you very much for the extension, it's working great!

Just a small suggestion regarding the design: As most users will mainly want to monitor power draw for me personally the "-" in front of the number isn't necessary, and takes up real estate in my task bar.  You could denote charging (positive rates) with a "+" still to make it distinct, or maybe have this as an option in the setting?
Similarly, as I'm mostly in single digit power draw I would prefer it if it said "5 W" instead of "-05 W", for readability and task bar space reasons, so no additional zeros for single digit power draw. You could add this as a setting as well.

Again, just some very minor suggestions, the extension is working great and I love it! If you don't agree feel free to just remove.

**Comment by halfmexican** [comment]
Great Suggestion. I would love to accommodate. This should be easy enough to add to settings, and I should probably re-evalaute what sane defaults look like

**Comment by halfmexican** [comment]
@thafluu added a new branch if you wanna test or make suggestions

**Comment by thafluu** [comment]
Hey, thank you for the reply! Gonna test it as soon as I can, and many thanks for the quick implementation!

**Comment by thafluu** [comment]
It's perfect, thanks a lot! Sadly Gnome auto-updates the extension to version 16 which is the one in the Gnome extensions repository after every reboot. But I'll just wait until the changes get merged, until then I use the regular version :) Thanks again!

**Comment by halfmexican** [comment]
Extension was just approved and published
