### ISSUE TITLE
Stuck on Calculating

### ISSUE THREAD

**Issue by Zaglim** [halfmexican/battery-usage-wattmeter-extension#6]
It's been 'Calculating'. I've tried manual battery selection in the extension's settings, system restart and performing charge cycles down to about 10% and back up to 100%.
```
Setup:
 OS: Fedora Linux 39 (Workstation Edition) x86_64 
 DE: GNOME 45.0
 Device:  Framework 13 - 12th gen Intel  CPU
```

I had this extension working flawlessly for me on Pop!_OS 22.04 (GNOME 44 I think) on the same computer just a few weeks ago. One of my favorite extensions!
Any ideas for a fix?

![Screenshot from 2023-11-01 11-32-01](https://github.com/halfmexican/battery-usage-wattmeter-extension/assets/41408139/0edbfd5a-b062-44e9-9d70-b2e060338e9f)

**Comment by halfmexican** [comment]
Hi! What device are you using? I think the issue may exist in how I have the  pref.js set up

**Comment by Zaglim** [comment]
## Resolved/Fixed!
Manually selected BAT1 and it's working now. Your changes last week must have fixed the issue - whatever it was.
Thanks!
