### ISSUE TITLE
Extension fails to attach to bar

### ISSUE THREAD

**Issue by 4JX** [halfmexican/battery-usage-wattmeter-extension#7]
The extension seems to silently fail to "attach" itself to the control panel tab on boot if `dash-to-panel` is enabled. However disabling and enabling the (wattmeter) extension again fixes the issue, after which I cannot reproduce the issue by disabling and enabling `dash-to-panel` as it all seemingly works fine after that.

Could not find any logs on `journalctl` about it.

**Comment by halfmexican** [comment]
I've recently tested running both extensions on both X11 and Wayland and the watt-meter successfully attached to the modified panel

**Comment by 4JX** [comment]
Did some very-not-scientific testing (lack of experience with debugging extensions). I had originally placed the blame on dash-to-panel as I assumed that it was the most probable cause as compared to a "vanilla" system but I seemed to forget to test without it.

It seems the point of failure is at this check:
https://github.com/halfmexican/battery-usage-wattmeter-extension/blob/94b1aaaa582a70e3dbd78fff3e5a36ed51d5a9e7/extension.js#L16-L18

[A few `console.error` later](https://github.com/4JX/battery-usage-wattmeter-extension/commit/eb95932a794216feaf8237e12f71206ac1d7ff11) I cannot get the "exists" lines to show up if I log out and back in:
```
»  journalctl -b 0 -r | rg "\[watt\]" 
...
Jan 28 17:34:30 terra .gnome-shell-wr[30885]: [watt] getBattStatus
Jan 28 17:34:30 terra .gnome-shell-wr[30885]: [watt] sync
Jan 28 17:34:26 terra .gnome-shell-wr[30885]: [watt] getBattStatus
Jan 28 17:34:26 terra .gnome-shell-wr[30885]: [watt] sync
Jan 28 17:34:22 terra .gnome-shell-wr[30885]: [watt] connect
Jan 28 17:34:22 terra .gnome-shell-wr[30885]: [watt] spawn
Jan 28 17:34:22 terra .gnome-shell-wr[30885]: [watt] spawn
Jan 28 17:34:22 terra .gnome-shell-wr[30885]: [watt] enable
```

But if I restart the extension everything goes fine:
```
»  journalctl -b 0 -r | rg "\[watt\]" 
...
Jan 28 17:42:16 terra .gnome-shell-wr[30885]: [watt] getBattStatus
Jan 28 17:42:16 terra .gnome-shell-wr[30885]: [watt] sync
Jan 28 17:42:12 terra .gnome-shell-wr[30885]: [watt] getBattStatus
Jan 28 17:42:12 terra .gnome-shell-wr[30885]: [watt] sync
Jan 28 17:42:08 terra .gnome-shell-wr[30885]: [watt] connect
Jan 28 17:42:08 terra .gnome-shell-wr[30885]: [watt] toggle exists
Jan 28 17:42:08 terra .gnome-shell-wr[30885]: [watt] system exists
Jan 28 17:42:08 terra .gnome-shell-wr[30885]: [watt] spawn
Jan 28 17:42:08 terra .gnome-shell-wr[30885]: [watt] spawn
Jan 28 17:42:08 terra .gnome-shell-wr[30885]: [watt] enable
Jan 28 17:42:06 terra .gnome-shell-wr[30885]: [watt] stop
Jan 28 17:42:06 terra .gnome-shell-wr[30885]: [watt] disable
...
```

Every other extension in my system was disabled during testing

**Comment by halfmexican** [comment]
will keep looking into this

**Comment by halfmexican** [comment]
@4JX You wanna test [this branch](https://github.com/halfmexican/battery-usage-wattmeter-extension/tree/dtp-fix)?

**Comment by 4JX** [comment]
Seems to work now :+1:
